version: '3.2'

services:
  camunda:
    build: .
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Duser.timezone=America/Montreal
    ports:
      - "8080:8080"
    volumes:
      - /Users/MyUser/Documents/docker_volumes/csv_files:/csv_files
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge